### ISSUE TITLE
code is not understandable 

### ISSUE THREAD

**Issue by whqwill** [locuslab/icnn#4]
the code define the f function as ：

    def f_ficnn(self, x, y, reuse=False):
        fc = tflearn.fully_connected
        xy = tf.concat((x, y), 1)

        prevZ = None
        for i, sz in enumerate([200, 200, 1]):
            z_add = []

            with tf.variable_scope('z_x{}'.format(i)) as s:
                z_x = fc(xy, sz, reuse=reuse, scope=s, bias=True)
                z_add.append(z_x)

            if prevZ is not None:
                with tf.variable_scope('z_z{}_proj'.format(i)) as s:
                    z_z = fc(prevZ, sz, reuse=reuse, scope=s, bias=False)
                    z_add.append(z_z)

            if sz != 1:
                z = tf.nn.relu(tf.add_n(z_add))
            prevZ = z

        return tf.contrib.layers.flatten(z)

it has two input : x and y. I think there should be only one input and y is output. Do I misunderstand something?

**Comment by whqwill** [comment]
further more, what is the meaning of xy?  
xy = tf.concat((x, y), 1)

**Comment by bamos** [comment]
Hi, thanks for going through the code so closely! The reason this portion has both inputs and outputs as input to the ICNN is because we are doing energy-based modeling. I recommend this tutorial as an introduction to these methods: http://yann.lecun.com/exdb/publis/pdf/lecun-06.pdf
